### ISSUE TITLE
Hash full ?

### ISSUE THREAD

**Issue by tissatussa** [jtseng20/Beef#2]
Using CuteChess i see the hash percentage of the engines which play against eachother. Many engines clear their hash before evaluating each new move, but the hash percentage of Beef v0.3.6 increases up to 100% and is never cleared !? I think this is a bug, but i can not test it - Beef keeps playing .. [EDIT: while testing, at this moment Beef does NOT suffer from this !? but i'm sure it happened ..]

I reported the same issue to the creator of the Marvin chess engine and he recently solved it, see https://github.com/bmdanielsson/marvin-chess/issues/8

**Comment by jtseng20** [comment]
As the author of Marvin notes, the thing you're describing is probably just in terms of number reporting, not a functionality bug. To quickly check if a hash table is being actually cleared, you could watch task manager for memory usage. Most engines do not actually clear their hash tables between moves, as that would actually be a bad idea for strength of play. I'm pretty sure that the described behavior doesn't happen, and I also didn't observe this behavior upon brief inspection, so maybe you observed it in a particular position that might cause something that looks similar, late in the game. Feel free to submit again if you document a replicable case.
